### PR TITLE
added test data handling

### PR DESCRIPTION
**Pull request by ggoffy**

### CODE REVIEW

**Comment by GregMage** [comment]
Hi,

Thanks for this work! A problem if I go to the module preferences: 

Error: Error: Undefined constant "CO_HTDOCS_SHOW_SAMPLE_BUTTON" in file /modules/system/admin/preferences/main.php line 297

**Comment by ggoffy** [comment]
can't reproduce. 
which version of XOOPS are you using?
when does the error occure exactly?

**Comment by GregMage** [comment]
This error appears when I go to the preferences of the xmnews module.

I have the updated version of xoops 2.5.11. Are the changes compatible with xoops 2.5.10?

**Comment by ggoffy** [comment]
> Are the changes compatible with xoops 2.5.10?

As far as I know 2.5.10 is not fully supporting namespaces. do you have the same problems with last version of 2.5.11 ?

**Comment by GregMage** [comment]
Same problems.I work only with 2.5.11

**Comment by ggoffy** [comment]
are you using english or french language files?

**Comment by GregMage** [comment]
english

**Comment by ggoffy** [comment]
found it, sorry, was my fault. please use last pull and run module update

**Comment by GregMage** [comment]
Very good work! Thank you

**Pull request merged**
